import { GoogleSpreadsheet } from "google-spreadsheet";
import { AppendOrUpdateValuesInputDto, GoogleSheetAuthenticateInput } from "../../../../../domain/repository/api/google/google-sheet/common.types";
import IGoogleSheetApiRepository from "./google-sheet-api.repository.interface";
import { JWT } from "google-auth-library";

export default class GoogleSheetApiV1Repository implements IGoogleSheetApiRepository {

  private doc: GoogleSpreadsheet | null = null;
  
  public async authenticate(input: GoogleSheetAuthenticateInput) {
    // Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
    const serviceAccountAuth = new JWT({
      // env var values here are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      email: input.email,
      key: input.key,
      scopes: ['https://www.googleapis.com/auth/spreadsheets'],
    });

    this.doc = new GoogleSpreadsheet('<the sheet ID from the url>', serviceAccountAuth);
  }

  public async appendRow(input: AppendOrUpdateValuesInputDto): Promise<void> {
    if(!this.doc) return;
    throw new Error("Method not implemented.");
  }

  public async updateRow(input: AppendOrUpdateValuesInputDto): Promise<void> {
    if(!this.doc) return;

    
    throw new Error("Method not implemented.");
  }
}
